### ISSUE TITLE
Website link broken

### ISSUE THREAD

**Issue by Dcanadian** [vassbo/logic#2]
Hello, just checking to see if this repo is still alive... Whenever I try to visit the website for this, I get this error message:
![Screen Shot 2024-05-14 at 1 53 49 PM](https://github.com/vassbo/logic/assets/139495555/20fbcf3f-fe0e-4205-a703-d40c245f8283)
Is this a bug?

**Comment by vassbo** [comment]
Netlify change their domain a few years back from .com to .app, but they did continue to redirect the old sites, looks like they does not do that anymore. Here is a working link: https://logics.netlify.app/
